import type {
  CostMetric,
  CostTraceGraph,
  FinishedBatchCostDetail,
  FinishedBatchCostSummary,
  ManufacturingCostGroup,
} from '../api/costData'

const metric = (amount: string, unitCost: string): CostMetric => ({ amount, unit_cost: unitCost })

const groups: ManufacturingCostGroup[] = [
  {
    group_code: 'direct_material',
    group_label: '一、直接材料',
    metric: metric('20000.00', '20.00'),
    share: '40.00',
    leaves: [
      { cost_code: 'raw_material', label: '原材料', metric: metric('20000.00', '20.00'), share: '40.00' },
      { cost_code: 'purchased_semi_finished', label: '外购半成品', metric: metric('0.00', '0.00'), share: '0.00' },
    ],
  },
  {
    group_code: 'direct_labor',
    group_label: '二、直接人工',
    metric: metric('8000.00', '8.00'),
    share: '16.00',
    leaves: [{ cost_code: 'direct_wages', label: '工资', metric: metric('8000.00', '8.00'), share: '16.00' }],
  },
  {
    group_code: 'direct_energy',
    group_label: '三、直接能耗',
    metric: metric('2000.00', '2.00'),
    share: '4.00',
    leaves: [{ cost_code: 'electricity', label: '电费', metric: metric('2000.00', '2.00'), share: '4.00' }],
  },
  {
    group_code: 'indirect_labor',
    group_label: '四、间接人工',
    metric: metric('4000.00', '4.00'),
    share: '8.00',
    leaves: [{ cost_code: 'indirect_wages', label: '工资', metric: metric('4000.00', '4.00'), share: '8.00' }],
  },
  {
    group_code: 'main_equipment_depreciation',
    group_label: '五、主设备折旧',
    metric: metric('3000.00', '3.00'),
    share: '6.00',
    leaves: [{ cost_code: 'equipment', label: '设备类', metric: metric('3000.00', '3.00'), share: '6.00' }],
  },
  {
    group_code: 'manufacturing_overhead',
    group_label: '六、制造费用',
    metric: metric('13000.00', '13.00'),
    share: '26.00',
    leaves: [{ cost_code: 'maintenance', label: '维修费', metric: metric('13000.00', '13.00'), share: '26.00' }],
  },
]

export const finishedBatch: FinishedBatchCostSummary = {
  finished_batch_id: 'batch-finished-1',
  event_id: 'event-root',
  part: {
    part_id: 'part-1',
    part_number: 'FG-001',
    part_description: '成品外壳总成',
    part_type: 'finished_good',
    product_family: '外饰件',
  },
  period: '2026-06',
  completion_time: '2026-06-30T08:30:00Z',
  cost_center_code: 'CC-400',
  cost_center_name: '装配车间',
  work_order_number: 'WO-202606-01',
  lot_number: 'LOT-FG-001',
  process_code: 'assembly',
  process_name: '装配',
  qualified_quantity: '950.0000',
  defective_quantity: '50.0000',
  completed_quantity: '1000.0000',
  quality_rate: '95.00',
  unit: '件',
  machine_hours: '12.00',
  labor_hours: '24.00',
  manufacturing_view: { groups, total: metric('50000.00', '50.00') },
  material_labor_overhead_view: {
    material: metric('20000.00', '20.00'),
    labor: metric('12000.00', '12.00'),
    overhead: metric('18000.00', '18.00'),
    total: metric('50000.00', '50.00'),
  },
  variable_fixed_view: {
    variable_cost_1: metric('30000.00', '30.00'),
    fixed_cost_1: metric('20000.00', '20.00'),
    manufacturing_total: metric('50000.00', '50.00'),
    after_sales_compensation: metric('1000.00', '1.00'),
    transportation: metric('2000.00', '2.00'),
    storage_fee: metric('500.00', '0.50'),
    variable_cost_2: metric('33000.00', '33.00'),
    fixed_cost_2: metric('20500.00', '20.50'),
    total_cost_2: metric('53500.00', '53.50'),
  },
}

const trace: CostTraceGraph = {
  root_event_id: 'event-root',
  nodes: [
    {
      event_id: 'event-root',
      event_type: 'process',
      output_batch_id: 'batch-finished-1',
      part: finishedBatch.part,
      completion_time: finishedBatch.completion_time,
      cost_center_code: 'CC-400',
      cost_center_name: '装配车间',
      work_order_number: 'WO-202606-01',
      lot_number: 'LOT-FG-001',
      process_code: 'assembly',
      process_name: '装配',
      qualified_quantity: '950.0000',
      defective_quantity: '50.0000',
      completed_quantity: '1000.0000',
      unit: '件',
      direct_costs: { items: [{ cost_code: 'direct_wages', cost_group: 'direct_labor', label: '工资', amount: '8000.00' }], total_amount: '8000.00' },
      inherited_costs: { items: [{ cost_code: 'raw_material', cost_group: 'direct_material', label: '原材料', amount: '20000.00' }], total_amount: '20000.00' },
      accumulated_costs: { items: [
        { cost_code: 'direct_wages', cost_group: 'direct_labor', label: '工资', amount: '8000.00' },
        { cost_code: 'raw_material', cost_group: 'direct_material', label: '原材料', amount: '20000.00' },
      ], total_amount: '28000.00' },
      display_unit_cost: '28.00',
      transfer_unit_cost: '29.47',
    },
    {
      event_id: 'event-paint',
      event_type: 'process',
      output_batch_id: 'batch-paint-1',
      part: { part_id: 'part-2', part_number: 'WIP-PAINT', part_description: '喷漆半成品', part_type: 'work_in_progress', product_family: '外饰件' },
      completion_time: '2026-06-20T08:00:00Z',
      cost_center_code: 'CC-200',
      cost_center_name: '喷漆车间',
      work_order_number: 'WO-PAINT-01',
      lot_number: 'LOT-PAINT-01',
      process_code: 'painting',
      process_name: '喷漆',
      qualified_quantity: '1000.0000',
      defective_quantity: '0.0000',
      completed_quantity: '1000.0000',
      unit: '件',
      direct_costs: { items: [], total_amount: '3000.00' },
      inherited_costs: { items: [], total_amount: '10000.00' },
      accumulated_costs: { items: [], total_amount: '13000.00' },
      display_unit_cost: '13.00',
      transfer_unit_cost: '13.00',
    },
    {
      event_id: 'event-material',
      event_type: 'purchase',
      output_batch_id: 'batch-material-1',
      part: { part_id: 'part-3', part_number: 'RM-ABS', part_description: 'ABS 原料', part_type: 'raw_material', product_family: null },
      completion_time: '2026-06-01T08:00:00Z',
      cost_center_code: null,
      cost_center_name: null,
      work_order_number: null,
      lot_number: 'LOT-RM-01',
      process_code: null,
      process_name: null,
      qualified_quantity: '1200.0000',
      defective_quantity: '0.0000',
      completed_quantity: '1200.0000',
      unit: 'kg',
      direct_costs: { items: [], total_amount: '10000.00' },
      inherited_costs: { items: [], total_amount: '0.00' },
      accumulated_costs: { items: [], total_amount: '10000.00' },
      display_unit_cost: '8.33',
      transfer_unit_cost: '8.33',
    },
  ],
  edges: [
    { input_id: 'input-material-root', source_event_id: 'event-material', target_event_id: 'event-root', consumed_quantity: '100.0000', unit: 'kg', allocation_ratio: '0.083333', allocated_costs: { items: [], total_amount: '833.00' } },
    { input_id: 'input-paint-root', source_event_id: 'event-paint', target_event_id: 'event-root', consumed_quantity: '950.0000', unit: '件', allocation_ratio: '0.950000', allocated_costs: { items: [], total_amount: '12350.00' } },
    { input_id: 'input-material-paint', source_event_id: 'event-material', target_event_id: 'event-paint', consumed_quantity: '1000.0000', unit: 'kg', allocation_ratio: '0.833333', allocated_costs: { items: [], total_amount: '8333.00' } },
  ],
  records: [
    {
      cost_record_id: 'record-root',
      event_id: 'event-root',
      cost_code: 'direct_wages',
      cost_group: 'direct_labor',
      cost_label: '工资',
      amount: '8000.00',
      currency: 'CNY',
      incurred_at: '2026-06-30T08:30:00Z',
      source_system: 'MES',
      source_document_no: 'PAY-001',
      source_document_line: '1',
      source_record_id: 'MES-PAY-001-1',
      raw_payload: {},
    },
    {
      cost_record_id: 'record-material',
      event_id: 'event-material',
      cost_code: 'raw_material',
      cost_group: 'direct_material',
      cost_label: '原材料',
      amount: '10000.00',
      currency: 'CNY',
      incurred_at: '2026-06-01T08:00:00Z',
      source_system: 'ERP',
      source_document_no: 'PO-001',
      source_document_line: '10',
      source_record_id: 'ERP-PO-001-10',
      raw_payload: {},
    },
  ],
}

export const finishedBatchDetail: FinishedBatchCostDetail = { ...finishedBatch, trace }
